# Generated by Django 5.0.6 on 2024-05-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
